name: Sync to namespaced format branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          pip install git-filter-repo
      - name: Sync to branch
        run: |
          git checkout -b temp-namespaced main
          git filter-repo --subdirectory-filter data/npc-v2 --force

          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:namespaced --force